services:
  - type: web
    name: realbroker-client
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    redirects:
      - source: /reset-password
        destination: /index.html
        status: 200
      - source: /forgot-password
        destination: /index.html
        status: 200
      - source: /*
        destination: /index.html
        status: 200
