services:
  - type: web
    name: realbroker-admin
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    redirects:
      - source: /reset-password
        destination: /index.html
        status: 200
      - source: /admin/*
        destination: /index.html
        status: 200
      - source: /*
        destination: /index.html
        status: 200
